"""add_meta_columns

Revision ID: db057b988dbe
Revises: 65a2ac06a5d7
Create Date: 2023-10-26 17:57:22.637154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db057b988dbe'
down_revision = '65a2ac06a5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('later_links', sa.Column('is_posted_to_discord', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('later_links', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('later_links', 'is_deleted')
    op.drop_column('later_links', 'is_posted_to_discord')
    # ### end Alembic commands ###
